## 판다스 기초

### 판다스 패키지 로드

```python
import pandas as pd
```

In [1]:
import pandas as pd

In [4]:
import numpy as np

#### 핵심 자료구조

- `Series`와 `DataFrame`

#### Series
- 1차원 데이터를 표현하는 자료구조. `인텍스가` 붙어있는 한줄짜리 데이터.1차원 배열과 흡사

In [9]:
scores = pd.Series([85, 90, 95, 88])

scores

0    85
1    90
2    95
3    88
dtype: int64

In [10]:
scores[0]

np.int64(85)

In [8]:
np_scores = np.array([85, 90, 95, 88])

np_scores

array([85, 90, 95, 88])

- 시리즈 작성 시 인덱스를 커스터마이징 할 수 있음

In [11]:
scores = pd.Series(
    [85, 90, 95, 88],
    index=['홍길동','김철수','이영희','박민수']
    )

scores

홍길동    85
김철수    90
이영희    95
박민수    88
dtype: int64

In [13]:
# 인텍스가 숫자에서 문자열로 변경.
scores['홍길동']

np.int64(85)

#### Series 연산

In [ ]:
# 화면에 출력되고 끝
scores +5

홍길동     90
김철수     95
이영희    100
박민수     93
dtype: int64

In [17]:
scores / 2

홍길동    42.5
김철수    45.0
이영희    47.5
박민수    44.0
dtype: float64

In [18]:
scores

홍길동    85
김철수    90
이영희    95
박민수    88
dtype: int64

In [19]:
scores.mean()

np.float64(89.5)

In [20]:
scores.max()

np.int64(95)

In [22]:
scores.std()

np.float64(4.203173404306164)

- NumPy와 유사하게 통계함수가 거의 유사하게 존재, pandas만 가지고도 가능
- 속도문제로 예전에는 NumPy를 많이 사용했지만, 현재는 사용효율이 높지 않음

#### DataFrame
- Pandas 2차원 표형태 데이터 표현하는 자료구조
- Pandas의 기본 자료구조형 
- 엑셀, CSV(엑셀형태 텍스트파일), DB 테이블과 거의 동일한 구조

In [32]:
# DataFrame을 직접 생성할때 사용.
raw_data = {
    'name': ['홍길동', '김철수', '이영희', '박민수','박민수', '성유고', '애슐리'],
    'age' : [20, 21, 22, 23, 22, 33],
    'major' : ['데이터분석', '웹개발', '인공지능', '임베디드','인공지능','웹개발'],
    'score' : [85, 90, 95, 80, 90, 100]

}

raw_data

{'name': ['홍길동', '김철수', '이영희', '박민수', '박민수', '성유고', '애슐리'],
 'age': [20, 21, 22, 23, 22, 33],
 'major': ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
 'score': [85, 90, 95, 80, 90, 100]}

In [33]:
# 일반적으로 DataFrame 줄여서 df로 변수형 많이 활용
df = pd.DataFrame(raw_data)

df

ValueError: All arrays must be of the same length

#### DataFrame 구조 확인
- NumPy 의 shape, size, dt

In [34]:
# 앞쪽 데이터 확인
df.head()

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80

In [36]:
# 앞쪽 데이터 확인 기본이 5
df.head(3)

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95

In [37]:
df.tail(2)

  name  age major  score
2  이영희   22  인공지능     95
3  박민수   23  임베디드     80

In [38]:
# 행과 열의 개수 
df.shape

(4, 4)

In [39]:
df.columns

Index(['name', 'age', 'major', 'score'], dtype='str')

In [40]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [41]:
# 컬럼별 타입과 결측값 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   major   4 non-null      str
 3   score   4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

#### 기본통계
- 수치타입만 나옴

In [42]:
df.describe()

             age      score
count   4.000000   4.000000
mean   21.500000  87.500000
std     1.290994   6.454972
min    20.000000  80.000000
25%    20.750000  83.750000
50%    21.500000  87.500000
75%    22.250000  91.250000
max    23.000000  95.000000

In [43]:
df.age.mean()

np.float64(21.5)

In [44]:
df['age'].mean()

np.float64(21.5)

In [45]:
df.age.median()

np.float64(21.5)

In [48]:
# 25% 값 / 1분위 수
df.age.quantile(0.25)

np.float64(20.75)

In [50]:
# 2분위 수 = median()
df.age.quantile(0.5)

np.float64(21.5)